apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-helm-charts.fullname" . }}
  labels:
    {{- include "my-helm-charts.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "my-helm-charts.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "my-helm-charts.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          # VolumeMounts must be indented under the container
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: ebs-data
              mountPath: {{ .Values.persistence.mountPath }}
          {{- end }}
      
      # Volumes must be at the Pod spec level (same level as containers)
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: ebs-data
          persistentVolumeClaim:
            claimName: {{ include "my-helm-charts.fullname" . }}-ebs-pvc
      {{- end }}
