apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "my-helm-charts.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                # Logic: If URL is preview, go to preview service. Else, go to active.
                name: {{ if eq .host "preview.chippy123.shop" }}bluegreen-preview{{ else }}bluegreen-active{{ end }}
                port:
                  number: 80
          {{- end }}
    {{- end }}
