apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "my-helm-charts.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host.host | quote }}
      http:
        paths:
          {{- range $host.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                # Use the variable $host to check the domain
                name: {{ if eq $host.host "preview.chippy123.shop" }}bluegreen-preview{{ else }}bluegreen-active{{ end }}
                port:
                  number: 80
          {{- end }}
    {{- end }}
