apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "my-helm-charts.fullname" . }}-ebs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ebs-sc # This must match the StorageClass name in your EKS
