apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: bluegreen-app
  namespace: default
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.service.selector }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.selector }}
    spec:
      containers:
      - name: flask-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.targetPort }}

        resources:   # ✅ REQUIRED for HPA
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

  strategy:
    blueGreen:
      activeService: bluegreen-active
      autoPromotionEnabled: false
