# 1. The Active Service (Live Traffic)
apiVersion: v1
kind: Service
metadata:
  name: bluegreen-active
spec:
  type: ClusterIP
  selector:
    # Note: Argo Rollouts will automatically add an additional 
    # 'rollouts-pod-template-hash' label here during a swap.
    app: {{ .Values.global.appLabel }}
  ports:
    - port: 80
      targetPort: 80
---
# 2. The Preview Service (Testing Traffic)
apiVersion: v1
kind: Service
metadata:
  name: bluegreen-preview
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.global.appLabel }}
  ports:
    - port: 80
      targetPort: 80
