apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-helm-charts.fullname" . }}-active
spec:
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: my-app
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-helm-charts.fullname" . }}-preview
spec:
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: my-app
