# 1. Global App Settings
global:
  appLabel: "my-helm-charts"

replicaCount: 2

image:
  repository: 113461832962.dkr.ecr.ap-south-1.amazonaws.com/bluegreenrepo
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

# 2. Service Settings (Routing to Flask on 5000)
service:
  type: ClusterIP
  port: 80
  targetPort: 5000

# 3. Ingress Settings
ingress:
  enabled: true
  className: "alb"
  annotations:
    alb.ingress.kubernetes.io/group.name: "chippy-prod-alb"
    alb.ingress.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:ap-south-1:113461832962:certificate/60d2857a-1d9a-486d-b943-04d8586e170d"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    # CRITICAL: ALB must check port 5000 for Flask
    alb.ingress.kubernetes.io/healthcheck-port: "5000"
    alb.ingress.kubernetes.io/healthcheck-path: "/"
  hosts:
    - host: chippy123.shop
      paths:
        - path: /
          pathType: Prefix

persistence:
  enabled: true
  mountPath: /data
  storageClass: ebs-sc
  size: 1Gi
