global:
  appLabel: "my-helm-charts"

replicaCount: 2

image:
  repository: 113461832962.dkr.ecr.ap-south-1.amazonaws.com/bluegreenrepo
  tag: "latest"

# CRITICAL: Fixes ArgoCD "Too Many Redirects"
server:
  extraArgs:
    - --insecure
ingress:
  enabled: true
  className: "alb"
  annotations:
    alb.ingress.kubernetes.io/group.name: "chippy-shared-lb"
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:ap-south-1:113461832962:certificate/60d2857a-1d9a-486d-b943-04d8586e170d"
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/healthcheck-port: "5000"
    alb.ingress.kubernetes.io/healthcheck-path: "/"
    alb.ingress.kubernetes.io/success-codes: "200-399"
  hosts:
    - host: chippy123.shop
      paths:
        - path: /
          pathType: Prefix
    - host: preview.chippy123.shop
      paths:
        - path: /
          pathType: Prefix
